# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
- 3.4
- oldrel
- release
- devel

env:
  global:
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true

after_success:
  - Rscript -e 'covr::codecov()'
